### ISSUE TITLE
Nomad Pack Beta (meta issue)

### ISSUE THREAD

**Issue by mikenomitch** [hashicorp/nomad-pack#308]
This is a meta issue for capturing the various things we want to do for the "beta" Pack release.

The contents of this are subject to change as we get further along:

Quality of Life Improvements:

- [ ] https://github.com/hashicorp/nomad-pack/issues/299
- [ ] https://github.com/hashicorp/nomad-pack/issues/188
- [ ] https://github.com/hashicorp/nomad-pack/issues/301
- [ ] https://github.com/hashicorp/nomad-pack/issues/25
- [ ] https://github.com/hashicorp/nomad-pack/issues/302
- [ ] https://github.com/hashicorp/nomad-pack/issues/296
- [ ] https://github.com/hashicorp/nomad-pack/issues/284
- [ ] Add ability to pass in HCL override blocks (to be further spec'd)

Structural Changes:
- [ ] https://github.com/hashicorp/nomad-pack/issues/304
- [ ] https://github.com/hashicorp/nomad-pack/issues/300
- [ ] Improve nested packs (better variable scoping, metadata access)
- [ ] Change "registry list" to list registries and add "list" for listing Packs

Bug Fixes:
- [ ] https://github.com/hashicorp/nomad-pack/issues/279

Outside of the Repo:
- [ ] Add Packs and Registries to Nomad-specific HashiCorp Integrations page (similar to [Vault's](https://developer.hashicorp.com/vault/integrations)).

**Comment by attachmentgenie** [comment]
@mikenomitch i would like to make a case for #153 and #266. These tickets describe IMHO reasonably annoying behavior that cause nomad-pack to behave different from vanilla nomad

**Comment by david-yu** [comment]
@angrycub Should we close this as well?
